Require lmchecksum
Set Theme "Catppuccin Frappe"
Set TypingSpeed 70ms
Set Height 500
Sleep 1s
Type "ls"
Sleep 0.3
Enter
Sleep 1s
Type "sha256sum v1.1.0.zip"
Enter
Sleep 1s
Type "lmchecksum v1.1.0.zip "
Sleep 0.1s
Hide
Type@1ms "b4cf846504952c01df2eeab19cb617a6164c98be3e96b33364343264012b518a"
Show
Sleep 1s
Enter
Sleep 1.5s
Type 'lmchecksum v1.1.0.zip "a wrong checksum"'
Sleep 0.5s
Enter
Sleep 4s

